# Generated by Django 4.2.7 on 2025-03-25 04:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_departement_staff_staffdepartement_candidatestaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='approval',
            field=models.CharField(default='not_approved', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='candidate',
            name='role',
            field=models.CharField(default='no_role', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='staff',
            name='candidate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='mainApp.candidate'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='departement',
            name='departement_room_number',
            field=models.IntegerField(),
        ),
    ]
