# Generated by Django 4.2.7 on 2025-03-25 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_alter_candidate_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='approval',
            field=models.CharField(default='not_approved', max_length=20),
        ),
    ]
