# Generated by Django 4.2.7 on 2025-03-26 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_alter_candidate_approval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='email',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='role',
        ),
    ]
